version: '3.8'

networks:
    test:
        external: false

services: 
    mongo:
      image: mongo:latest
      container_name: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
      networks:
        - test
      
      ports:
        - '27017:27017'
      restart: always
    web:
      hostname: node
      build:
        dockerfile: dockerfile
        context : ./
      env_file: ./.env
      networks:
        - test
      ports:
        - '3000'
      depends_on:
        - mongo
    nginx:
      image: nginx:latest
      container_name: nginx
      networks:
        - test
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      restart: always
      depends_on: 
        - web
      ports:
        - 80:80